[package]

name = "rusterize"
version = "0.0.1"
authors = ["Colin Sherratt <colin.sherratt@gmail.com>"]

[dependencies]
genmesh = "*"
cgmath = "*"

[dependencies.image]
git = "https://github.com/PistonDevelopers/image"

[dev-dependencies]
obj = "*"
