[package]
name = "rusterize"
version = "0.0.1"
authors = ["Colin Sherratt <colin.sherratt@gmail.com>"]

[lib]
name = "rusterize"
path = "src/lib.rs"

[dependencies]
genmesh = "*"
cgmath = "*"

[dependencies.image]
git = "https://github.com/PistonDevelopers/image"

[dependencies]
obj="*"
gfx="*"
glfw="*"
time="*"

[[example]]
name = "monkey"
path = "examples/monkey.rs"