[package]
name = "rusterize"
version = "0.0.1"
authors = ["Colin Sherratt <colin.sherratt@gmail.com>"]

[lib]
name = "rusterize"
path = "src/lib.rs"

[dependencies]
genmesh = "*"
cgmath = "*"

[dependencies.image]
git = "https://github.com/PistonDevelopers/image"

[dependencies]
obj="*"
glfw="*"
time="*"
rand="*"
simd="*"
llvmint="*"

[[example]]
name = "monkey"
path = "examples/monkey.rs"

[[example]]
name = "cull"
path = "examples/cull.rs"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs.git"

[dependencies.gfx_device_gl]
git = "https://github.com/gfx-rs/gfx_device_gl.git"